/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    pages: Page;
    services: Service;
    cases: Case;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL path: /blog/your-slug
   */
  slug: string;
  category: 'Strategy' | 'Positioning' | 'Performance' | 'Brand systems';
  /**
   * Card kicker — e.g. Growth Strategy, Macro Trend
   */
  label: string;
  excerpt: string;
  featuredImage?: (number | null) | Media;
  author: string;
  /**
   * Display string, e.g. "8 min read"
   */
  readTime: string;
  /**
   * Show as hero on /blog
   */
  featured?: boolean | null;
  /**
   * Display date; use Schedule in sidebar for future publish
   */
  publishedAt: string;
  sections?:
    | {
        heading: string;
        /**
         * Optional image shown under this section heading
         */
        image?: (number | null) | Media;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Internal page name in admin
   */
  title: string;
  /**
   * URL key: home, about, contact, services, products, cases, audit, seo, blog
   */
  slug: string;
  hero?: {
    /**
     * Small label above the headline
     */
    tag?: string | null;
    /**
     * Each line becomes one row in the hero headline
     */
    titleLines?:
      | {
          line: string;
          id?: string | null;
        }[]
      | null;
    subheading?: string | null;
    /**
     * Secondary paragraph under the subheading
     */
    body?: string | null;
    image?: (number | null) | Media;
    ctaPrimaryLabel?: string | null;
    ctaPrimaryUrl?: string | null;
    ctaSecondaryLabel?: string | null;
    ctaSecondaryUrl?: string | null;
  };
  /**
   * Use sectionKey to identify blocks (studio, manifesto, verticals, includes, sprint, marathon, etc.)
   */
  sections?:
    | {
        /**
         * e.g. studio, manifesto, verticals, form, includes
         */
        sectionKey: string;
        tag?: string | null;
        heading?: string | null;
        subheading?: string | null;
        body?: string | null;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        items?:
          | {
              title?: string | null;
              body?: string | null;
              label?: string | null;
              value?: string | null;
              url?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        prefix?: string | null;
        value: string;
        suffix?: string | null;
        label: string;
        /**
         * Optional counter target number
         */
        animateTo?: number | null;
        id?: string | null;
      }[]
    | null;
  metaCards?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    eyebrow?: string | null;
    email?: string | null;
    location?: string | null;
    locationNote?: string | null;
    formPlaceholder?: string | null;
    submitLabel?: string | null;
    submitSuccessLabel?: string | null;
    socialLinks?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    title?: string | null;
    titleAccent?: string | null;
    primaryLabel?: string | null;
    primaryUrl?: string | null;
    secondaryLabel?: string | null;
    secondaryUrl?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * URL: /services/your-slug
   */
  slug: string;
  shortName: string;
  tagline: string;
  accent?: string | null;
  hero: {
    /**
     * Hero word after "Be"
     */
    word: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    primaryCta?: string | null;
  };
  blocks?:
    | {
        n: string;
        title: string;
        subtitle: string;
        sections?:
          | {
              heading: string;
              items?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        notes?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        cta?: string | null;
        id?: string | null;
      }[]
    | null;
  outcomes: {
    title: string;
    items?:
      | {
          title: string;
          body: string;
          bullets?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    extraTitle?: string | null;
    extraItems?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  socialProof: {
    title: string;
    cases?:
      | {
          quote?: string | null;
          attribution?: string | null;
          label?: string | null;
          metrics?:
            | {
                value: string;
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  closingQuote?: string | null;
  footerCta?: string | null;
  /**
   * Optional image for /services index card
   */
  cardImage?: (number | null) | Media;
  /**
   * Optional extra images inside service page
   */
  gallery?:
    | {
        title?: string | null;
        body?: string | null;
        label?: string | null;
        value?: string | null;
        url?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  client: string;
  /**
   * URL: /cases/your-slug
   */
  slug: string;
  niche: 'AI SaaS' | 'Fintech' | 'Cybersecurity' | 'iGaming';
  format: 'Sprint' | 'Marathon';
  duration: string;
  preview: string;
  headline: string;
  situation: string;
  challenge: string;
  resultsBody: string;
  accent?: string | null;
  coverImage: number | Media;
  heroImage?: (number | null) | Media;
  heroMetrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  primaryMetric: {
    value: string;
    label: string;
  };
  work?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  resultMetrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  quote: {
    text: string;
    who: string;
    role: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Source path, e.g. /old-page
   */
  from: string;
  /**
   * Destination path or full URL
   */
  to: string;
  type?: ('301' | '302') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  label?: T;
  excerpt?: T;
  featuredImage?: T;
  author?: T;
  readTime?: T;
  featured?: T;
  publishedAt?: T;
  sections?:
    | T
    | {
        heading?: T;
        image?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        tag?: T;
        titleLines?:
          | T
          | {
              line?: T;
              id?: T;
            };
        subheading?: T;
        body?: T;
        image?: T;
        ctaPrimaryLabel?: T;
        ctaPrimaryUrl?: T;
        ctaSecondaryLabel?: T;
        ctaSecondaryUrl?: T;
      };
  sections?:
    | T
    | {
        sectionKey?: T;
        tag?: T;
        heading?: T;
        subheading?: T;
        body?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        items?:
          | T
          | {
              title?: T;
              body?: T;
              label?: T;
              value?: T;
              url?: T;
              image?: T;
              id?: T;
            };
        id?: T;
      };
  stats?:
    | T
    | {
        prefix?: T;
        value?: T;
        suffix?: T;
        label?: T;
        animateTo?: T;
        id?: T;
      };
  metaCards?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        email?: T;
        location?: T;
        locationNote?: T;
        formPlaceholder?: T;
        submitLabel?: T;
        submitSuccessLabel?: T;
        socialLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        titleAccent?: T;
        primaryLabel?: T;
        primaryUrl?: T;
        secondaryLabel?: T;
        secondaryUrl?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortName?: T;
  tagline?: T;
  accent?: T;
  hero?:
    | T
    | {
        word?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        primaryCta?: T;
      };
  blocks?:
    | T
    | {
        n?: T;
        title?: T;
        subtitle?: T;
        sections?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        notes?:
          | T
          | {
              text?: T;
              id?: T;
            };
        cta?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        extraTitle?: T;
        extraItems?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  socialProof?:
    | T
    | {
        title?: T;
        cases?:
          | T
          | {
              quote?: T;
              attribution?: T;
              label?: T;
              metrics?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  closingQuote?: T;
  footerCta?: T;
  cardImage?: T;
  gallery?:
    | T
    | {
        title?: T;
        body?: T;
        label?: T;
        value?: T;
        url?: T;
        image?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  client?: T;
  slug?: T;
  niche?: T;
  format?: T;
  duration?: T;
  preview?: T;
  headline?: T;
  situation?: T;
  challenge?: T;
  resultsBody?: T;
  accent?: T;
  coverImage?: T;
  heroImage?: T;
  heroMetrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  primaryMetric?:
    | T
    | {
        value?: T;
        label?: T;
      };
  work?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  resultMetrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        who?: T;
        role?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerLinks?:
    | {
        label: string;
        /**
         * Internal path (/blog) or external URL
         */
        url: string;
        /**
         * Mobile menu subtitle
         */
        sub?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional extra links for dropdown menus
   */
  dropdownLinks?:
    | {
        label: string;
        url: string;
        /**
         * Parent header label, e.g. Services
         */
        parent?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  defaultMetaDescription?: string | null;
  /**
   * Full robots.txt content served at /robots.txt on the public site
   */
  robotsTxt?: string | null;
  blogMetaTitle?: string | null;
  blogMetaDescription?: string | null;
  blogIndex?: {
    seasonLabel?: string | null;
    issuedBy?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
    lead?: string | null;
    featuredLabel?: string | null;
    archiveLabel?: string | null;
    allEntriesLabel?: string | null;
    emptyArchive?: string | null;
    resetFilters?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        sub?: T;
        id?: T;
      };
  dropdownLinks?:
    | T
    | {
        label?: T;
        url?: T;
        parent?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultMetaDescription?: T;
  robotsTxt?: T;
  blogMetaTitle?: T;
  blogMetaDescription?: T;
  blogIndex?:
    | T
    | {
        seasonLabel?: T;
        issuedBy?: T;
        titleLine1?: T;
        titleLine2?: T;
        lead?: T;
        featuredLabel?: T;
        archiveLabel?: T;
        allEntriesLabel?: T;
        emptyArchive?: T;
        resetFilters?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'cases';
          value: number | Case;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}